offline:
  name: offline
  description: offline stage
  concurrency: 1
  commands:
    - path: /home/hadoop/OLAPBenchmark/lib
      command: hive -f kylin-tpch-create-views.sql
online:
  name: online
  description: online stage
  concurrency: 1
  loop: 10
  queries:
    - Q2
    - Q3
    - Q5
    - Q7
    - Q8
    - Q9
    - Q10
    - Q11
