offline:
  name: offline
  description: offline stage
  concurrency: 1
  commands:
    - path: ./lib/
      command: python3 kylin_cubing.py TPCH_Q1
online:
  name: online
  description: online stage
  concurrency: 1
  queries:
    - KQ1