offline:
  name: offline
  description: offline stage
  commands:
    - path: /home/experiment/wutongyu/tpch-kit/dbgen
      command: ls
online:
  name: online
  description: online stage
  queries:
    - Q1
    - Q2
