offline:
  name: offline
  description: offline stage
  concurrency: 1
  commands:
    - path: /home/hadoop/tpch-kit/dbgen
      command: ls
online:
  name: online
  description: online stage
  concurrency: 3
  queries:
    - Q1
    - Q2