offline:
  name: offline
  description: offline stage
  commands:
    - path: /home/hadoop/tpch-kit/dbgen
      command: ls
online:
  name: online
  description: online stage
  queries:
    - Q1
    - Q2
    - Q3
    - Q4
    - Q5
    - Q6
    - Q7
    - Q8
    - Q9
    - Q10
    - Q11
    - Q12
    - Q13
    - Q14
    - Q15b
    - Q15
    - Q15a
    - Q16
    - Q17
    - Q18
    - Q19
    - Q20
    - Q21
    - Q22
