offline:
  name: offline
  description: offline stage
  concurrency: 1
  commands:
    - path: ./lib/
      command: python3 kylin_cubing.py
online:
  name: online
  description: online stage
  concurrency: 3
  queries:
    - Q1
    - Q2