Queries:
  - AtSecond: 0.0
    ID: Q3
  - AtSecond: 1.0
    ID: Q1
  - AtSecond: 2.0
    ID: Q2
  - AtSecond: 3.0
    ID: Q2
  - AtSecond: 4.0
    ID: Q3
  - AtSecond: 5.0
    ID: Q2
  - AtSecond: 6.0
    ID: Q3
  - AtSecond: 7.0
    ID: Q1
  - AtSecond: 8.0
    ID: Q3
  - AtSecond: 9.0
    ID: Q2
  - AtSecond: 10.0
    ID: Q3
  - AtSecond: 11.0
    ID: Q3
  - AtSecond: 12.0
    ID: Q2
  - AtSecond: 13.0
    ID: Q2
  - AtSecond: 14.0
    ID: Q2
  - AtSecond: 15.0
    ID: Q3
  - AtSecond: 16.0
    ID: Q3
  - AtSecond: 17.0
    ID: Q2
  - AtSecond: 18.0
    ID: Q3
