name: SparkSQL-TPCH
config:
  hive.metastore.uris: thrift://ip-172-31-23-194.ap-southeast-1.compute.internal:9083
  spark.sql.warehouse.dir: hdfs://ip-172-31-23-194.ap-southeast-1.compute.internal:8020/user/hive/warehouse
