Name: Spark-SQL
Config:
  hive.metastore.uris: thrift://localhost:9083
  hive.metastore.connect.retries: 3
  hive.metastore.client.factory.class: com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
  spark.sql.warehouse.dir: hdfs://localhost:8020/user/spark/warehouse