###############################################################################
# Cloud
###############################################################################

Cloud:
  Name: AWS
  Description: Amazon Web Service.
  Properties:
    Region: ap-southeast-1
    Ec2KeyName: key_raven
    MasterInstaceCount: 1
    MasterInstanceType: m5.xlarge
    CoreInstanceCount: 4
    CoreInstanceType: m5.4xlarge

###############################################################################
# Engine
###############################################################################

#Engine:
#  Name: hive
#  Description: Hive.
#  Properties:
#    Concurrency: 1

#Engine:
#  Name: spark_sql
#  Description: Spark-SQL.
#  Properties:
#    concurrency: 1

#Engine:
#  Name: presto
#  Description: Presto.
#  Properties:
#    host: localhost
#    port: 8080
#    user: hive
#    catalog: hive
#    concurrency: 1

#Engine:
#  Name: athena
#  Description: AWS Athena.
#  Properties:
#    concurrency: 1
#    region: ap-southeast-1

Engine:
  Name: kylin4
  Description: Apache Kylin 4.
  Properties:
    host: localhost
    port: 7070
    concurrency: 1

###############################################################################
# Testplan
###############################################################################

# PlanID:
#   Name:
#   Description
#   Properties:
#     Type: The type of test plan, allowed values are pipeline/timeline.
#     Path: The path of test plan config file.

Testplan:
  Name: SSB hybrid 1g timeline test.
  Description:
  Properties:
    Type: Timeline
    Path: config/testplan/template/timeline_template.yaml


###############################################################################
# Workload
###############################################################################

#Workload:
#  Name: SSB
#  Type: QPS
#  Parameters:
#    Database: ssb_flat_tbl_100
#    distribution: uniform
#    duration: 10
#    qps: 0.1

#Workload:
#  Name: SSB
#  Type: LOOP
#  Parameters:
#    Database: ssb_1g
#    loops: 2

#Workload:
#  Name: SSB
#  Type: Timeline
#  Parameters:

#Workload:
#  Name: SSB_KYLIN4
#  Type: LOOP
#  Parameters:
#    Database: ssb_flat_tbl_100
#    loops: 3

#Workload:
#  Name: SSB
#  Type: QPS
#  Parameters:
#    distribution: poisson
#    duration: 60
#    lam: 3.0

#Workload:
#  Name: SSB
#  Type: QPS
#  Parameters:
#    distribution: unimodal
#    duration: 60
#    max_qps: 3.0

#Workload:
#  Name: SSB
#  Type: QPS
#  Parameters:
#    distribution: bimodal
#    duration: 60
#    max_qps: 3.0

#Workload:
#  Name: SSB
#  Type: QPS
#  Parameters:
#    distribution: increase
#    duration: 60
#    max_qps: 3.0

#Workload:
#  Name: SSB
#  Type: QPS
#  Parameters:
#    distribution: surge
#    duration: 60
#    max_qps: 3.0
#    surge_time: 20
#    end: 40

#Workload:
#  Name: SSB
#  Type: QPS
#  Parameters:
#    distribution: sudden_shrink
#    duration: 60
#    max_qps: 3.0
#    shrink_time: 50

Workload:
  Name: Custom
  Type: Timeline
  Parameters:
    path: config/workload/kylin-custom.yaml