###############################################################################
# Cloud Provider
###############################################################################

Provider:
  Name: AWS
  Description: Amazon Web Service.
  Properties:
    Region: ap-southeast-1
    KeyName: key_raven
    MasterInstaceCount: 1
    CoreInstanceCount: 10

###############################################################################
# Engine
###############################################################################

#Engine:
#  Name: hive
#  Description: Hive.
#  Properties:
#    Concurrency: 1

#Engine:
#  Name: spark_sql
#  Description: Spark-SQL.
#  Properties:
#    concurrency: 1

#Engine:
#  Name: presto
#  Description: Presto-0.266.1.
#  Properties:
#    host: localhost
#    port: 8080
#    user: hive
#    catalog: hive
#    concurrency: 1

#Engine:
#  Name: athena
#  Description: AWS Athena.
#  Properties:
#    Concurrency: 1
#    Region: ap-southeast-1

#Engine:
#  Name: kylin4
#  Description: Apache Kylin 4.
#  Properties:
#    Concurrency: 1

###############################################################################
# Testplan
###############################################################################

# PlanID:
#   Name:
#   Description
#   Properties:
#     Type: The type of test plan, allowed values are pipeline/timeline.
#     Path: The path of test plan config file.

Testplan:
  Name: SSB hybrid 1g timeline test.
  Description:
  Properties:
    Type: Timeline
    Path: config/testplan/template/timeline_template.yaml


###############################################################################
# Workload
###############################################################################

Workload:
  Name: SSB
  Type: QPS
  Parameters:
    Database: ssb_1g
    distribution: uniform
    duration: 10.0
    qps: 1.0

#Workload:
#  ConfigPath: configs/workloads/ssb_hybrid_1g/workload.yaml
#  Parameters:
#    distribution: poisson
#    duration: 60
#    lam: 3.0

#Workload:
#  ConfigPath: configs/workloads/ssb_hybrid_1g/workload.yaml
#  Parameters:
#    distribution: unimodal
#    duration: 60
#    max_qps: 3.0

#Workload:
#  ConfigPath: configs/workloads/ssb_hybrid_1g/workload.yaml
#  Parameters:
#    distribution: bimodal
#    duration: 60
#    max_qps: 3.0

#Workload:
#  ConfigPath: configs/workloads/ssb_hybrid_1g/workload.yaml
#  Parameters:
#    distribution: increase
#    duration: 60
#    max_qps: 3.0

#Workload:
#  ConfigPath: configs/workloads/ssb_hybrid_1g/workload.yaml
#  Parameters:
#    distribution: surge
#    duration: 60
#    max_qps: 3.0
#    surge_time: 20
#    end: 40

#Workload:
#  ConfigPath: configs/workloads/ssb_hybrid_1g/workload.yaml
#  Parameters:
#    distribution: sudden_shrink
#    duration: 60
#    max_qps: 3.0
#    shrink_time: 50
