AWSTemplateFormatVersion: 2010-09-09
Description: Create Cluster for ec2 instances and deploy related services, hadoop/spark/zookeeper/hive/jdk/kylin4
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances.
    Type: AWS::EC2::KeyPair::KeyName
    Default: key_raven
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  Ec2CRRValue:
    Type: String
    Default: 202110180016
    AllowedValues:
      - 202110180016
  Ec2Mode:
    Type: String
    Default: test
    AllowedValues:
      - test
      - product
  DistributionScriptFileName:
    Type: String
    Default: prepare-ec2-env-for-distribution.sh
  Ec2InstanceTypeForDistribution:
    Description: EC2 instance type
    Type: String
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m5.xlarge
    AllowedValues:
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
  Ec2InstanceTypeForDistributionForTest:
    Description: EC2 instance type
    Type: String
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m5.xlarge
    AllowedValues:
      - m5.xlarge
  Ec2VolumeSizeForDistributionNode:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 30
  Ec2VolumnTypeForDistributionNode:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
      - gp3
      - io1
      - io2
      - sc1
      - st1
      - standard
  Ec2VolumeSizeForDistributionNodeForTest:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 20
  Ec2VolumnTypeForDistributionNodeForTest:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
Rules:
  KeyNameIsNotNull:
    Assertions:
      - Assert: !Not [!Equals [!Ref KeyName, ""]]
        Description: KeyName must not be empty.
  CRRIsNotNull:
    Assertions:
      - Assert: !Not [!Equals [!Ref Ec2CRRValue, ""]]
        Description: CRR must not be empty.
Mappings:
  AWSRegionArch2AMI:
    cn-north-1:
      HVMebs: ami-00ac27054b887ff5c
    cn-northwest-1:
      HVMebs: ami-0135cb179d33fbe3e
    ap-southeast-1:
      HVMebs: ami-07191cf2912e097a6
Conditions:
  IsProductMode: !Equals [!Ref Ec2Mode, "product"]
  IsAssociatedPublicIp: !Equals [!Ref AssociatedPublicIp, "true"]
Resources:
  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2_Kylin4_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AmazonEC2FullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'cloudwatch:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'autoscaling:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:CreateServiceLinkedRole'
                Resource: '*'
                Condition:
                  StringEquals:
                    iam:AWSServiceName:
                      - 'utoscaling.amazonaws.com'
                      - 'ec2scheduled.amazonaws.com'
                      - 'elasticloadbalancing.amazonaws.com'
                      - 'spot.amazonaws.com'
                      - 'spotfleet.amazonaws.com'
                      - 'transitgateway.amazonaws.com'
        - PolicyName: AmazonS3FullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                  - 's3-object-lambda:*'
                Resource: '*'
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn:
      - EC2IAMRole
    Properties:
      InstanceProfileName: EC2_Kylin4_Instance_Profile
      Path: /
      Roles:
        - !Ref EC2IAMRole
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - EC2InstanceProfile
    Properties:
      KeyName: !Ref KeyName
      InstanceType: !If
        - IsProductMode
        - !Ref Ec2InstanceTypeForDistribution
        - !Ref Ec2InstanceTypeForDistributionForTest
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref AWS::Region
        - HVMebs
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          Description: Auto create for Master node in benchmark
          AssociatePublicIpAddress: True
          DeleteOnTermination: True
          SubnetId:
            Fn::ImportValue: !Join [ ":", [ "Kylin4", "EC2", "Subnet" ] ]
          GroupSet:
            - Fn::ImportValue: !Join [ ":", [ "Kylin4", "EC2", "SecurityGroup" ] ]
      BlockDeviceMappings:
        - !If
          - IsProductMode
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref Ec2VolumeSizeForDistributionNode
              VolumeType: !Ref Ec2VolumnTypeForDistributionNode
              DeleteOnTermination: true
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref Ec2VolumeSizeForDistributionNodeForTest
              VolumeType: !Ref Ec2VolumnTypeForDistributionNodeForTest
              DeleteOnTermination: true
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash -xe
              cd /home/ec2-user
              aws s3 cp ${PrivateBucketFullPath}/scripts/${PrivateDistributionScriptFileName} .
              bash ${PrivateDistributionScriptFileName} --bucket-url ${PrivateBucketPath} --region ${PrivateRegion}
            - PrivateBucketFullPath: !Ref BucketFullPath
              PrivateDistributionScriptFileName: !Ref DistributionScriptFileName
              PrivateBucketPath: !Ref BucketPath
              PrivateRegion: !Ref AWS::Region
      Tags:
        - Key: Project
          Value: Raven
        - Key: Name
          Value: Distribution Node
        - Key: CRR
          Value: !Ref Ec2CRRValue
        - Key: OLAP Engine
          Value: Kylin4
Outputs:
  # Env parameters
  EC2InstanceProfile:
    Description: Instance profile for cluster
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Join [ ":", [ "Kylin4", "EC2", "InstanceProfile" ] ]
  # Instance parameters
  EC2Instance:
    Description: the id of Distribution Node Innstance
    Value: !Ref EC2Instance
  EC2InstancePrivateIp:
    Description: Distribution Private IP
    Value: !GetAtt EC2Instance.PrivateIp
