AWSTemplateFormatVersion: 2010-09-09
Description: Create Master nodes for ec2 instances and deploy related services, hadoop/spark/zookeeper/hive/jdk/kylin4
Parameters:
  Ec2DbHost:
    Type: String
    Description: Must be created at pre-step, db from ec2 instance
  Ec2DbUser:
    Type: String
    Description: Must be created at pre-step
    Default: root
  Ec2DbPassword:
    Type: String
    Description: Must be created at pre-step and this can be modified in the script not yaml file.
    Default: 123456
  Ec2ZookeeperkHost:
    Type: String
    Description: Must be created at pre-step, default is same as Ec2DbHost
  Ec2KylinMode:
    Type: String
    Description: Kylin mode for cluster, default is all, values in [all, query, job]
    Default: all
    AllowedValues:
      - all
      - query
      - job
  AssociatedPublicIp:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  Ec2WaitingTime:
    Type: Number
    Default: 200
    Description: sleep time to waitring services started in master node
  Ec2Mode:
    Type: String
    Default: test
    AllowedValues:
      - test
      - product
    Description: set the flag for Mode, if not test use product's configuration
  Ec2CRRValue:
    Type: String
    Default: 202110180016
    AllowedValues:
      - 202110180016
  BucketFullPath:
    Type: String
    Default: s3://chenyi-ap-southeast-1/kylin4
  BucketPath:
    Type: String
    Default: /chenyi-ap-southeast-1/kylin4
    Description: Url without prefix s3:/
  MasterScriptFileName:
    Type: String
    Default: prepare-ec2-env-for-master.sh
  InstanceType:
    Type: String
    Description: EC2 instance type
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m5.xlarge
    AllowedValues:
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
  InstanceTypeForTest:
    Type: String
    Description: EC2 instance type
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m5.2xlarge
    AllowedValues:
      - m5.2xlarge
  Ec2VolumnTypeForMasterNode:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
      - gp3
      - io1
      - io2
      - sc1
      - st1
      - standard
  Ec2VolumeSizeForMasterNode:
    Type: Number
    Default: 30
    MinValue: 30
    MaxValue: 100
  Ec2VolumnTypeForMasterNodeForTest:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
  Ec2VolumeSizeForMasterNodeForTest:
    Type: Number
    Default: 30
    MinValue: 30
    MaxValue: 30
Ruels:
  NotNullDbHost:
    Assertions:
      - Assert: !Not [!Equals [!Ref Ec2DbHost, ""]]
  NotNullDbPass:
    Assertions:
      - Assert: !Not [!Equals [!Ref Ec2DbPassword, ""]]
  NotNullDbUser:
    Assertions:
      - Assert: !Not [!Equals [!Ref Ec2DbUser, ""]]
  NotNullZkHost:
    Assertions:
      - Assert: !Not [!Equals [!Ref Ec2ZookeeperkHost, ""]]
  NotNullKylinMode:
    Assertions:
      - Assert: !Not [!Equals [!Ref Ec2KylinMode, ""]]
  NotNullCRR:
    Assertions:
      - Assert: !Not [!Equals [!Ref Ec2CRRValue, ""]]
  MustBeCRRValue:
    Assertions:
      - Assert: !Equals [!Ref Ec2CRRValue, "202110180016"]
Mappings:
  AWSRegionArch2AMI:
    cn-north-1:
      HVMebs: ami-00ac27054b887ff5c
    cn-northwest-1:
      HVMebs: ami-0135cb179d33fbe3e
    ap-southeast-1:
      HVMebs: ami-07191cf2912e097a6
Conditions:
  IsProductMode: !Equals [!Ref Ec2Mode, "product"]
  IsAssociatedPublicIp: !Equals [!Ref AssociatedPublicIp, "true"]
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
    Properties:
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref AWS::Region
        - HVMebs
      Tags:
        - Key: Cost Center
          Value: OS
        - Key: Project
          Value: Raven
        - Key: Engine
          Value: Kylin4
        - Key: CRR
          Value: !Ref Ec2CRRValue
        - Key: Name
          Value: Master Node for kylin4
      InstanceType: !If
          - IsProductMode
          - !Ref InstanceType
          - !Ref InstanceTypeForTest
      IamInstanceProfile:
        Fn::ImportValue: [ !Join [ ":", [ "Kylin4", 'EC2', 'InstanceProfile' ] ] ]
      NetworkInterfaces:
        - DeviceIndex: 0
          Description: Auto create for Master node in benchmark
          DeleteOnTermination: true
          AssociatePublicIpAddress: !Ref AssociatedPublicIp
          SubnetId: !Ref PublicSubnetID
          GroupSet:
            - Fn::ImportValue: !Join [ ":", [ "Kylin4", 'EC2', 'SecurityGroup' ] ]
      BlockDeviceMappings:
        - !If
          - IsProductMode
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref Ec2VolumeSizeForMasterNode
              VolumeType: !Ref Ec2VolumnTypeForMasterNode
              DeleteOnTermination: true
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref Ec2VolumeSizeForMasterNodeForTest
              VolumeType: !Ref Ec2VolumnTypeForMasterNodeForTest
              DeleteOnTermination: true
      KeyName:
        Fn::ImportValue: !Join [ ":", [ "Kylin4", "EC2", "KeyName" ] ]
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash -xe
              cd /home/ec2-user
              aws s3 cp ${PrivateBucketFullPath}/scripts/${PrivateMasterScriptFileName} . --region ${PrivateRegion}
              bash ${PrivateMasterScriptFileName} --bucket-url ${PrivateBucketPath} --region ${PrivateRegion} --db-host ${PrivateDbHost} --db-password ${PrivateDbPass} --db-user ${PrivateDbUser}  --zookeeper-host ${PrivateZkHost} --kylin-mode ${PrivaiteKylinMode} --waiting-time ${PrivateWaitingTime}
              echo " Master is ready ..."
            - PrivateBucketFullPath:
                Fn::ImportValue: !Join [ ":", [ "Kylin4", "S3", "BucketFullPath" ] ]
              PrivateMasterScriptFileName: !Ref MasterScriptFileName
              PrivateBucketPath:
                Fn::ImportValue: !Join [ ":", [ "Kylin4", "S3", "BucketPath" ] ]
              PrivateRegion: !Ref AWS::Region
              PrivateDbHost: !Ref Ec2DbHost
              PrivateDbPass: !Ref Ec2DbPassword
              PrivateDbUser: !Ref Ec2DbUser
              PrivateZkHost: !Ref Ec2ZookeeperkHost
              PrivaiteKylinMode: !Ref Ec2KylinMode
              PrivateWaitingTime: !Ref Ec2WaitingTime
Outputs:
  MasterEc2InstanceId:
    Description: the id of Master Node Innstance
    Value: !Ref EC2Instance
  MasterEc2InstancePrivateIp:
    Description: Master Instance Private IP
    Value: !GetAtt EC2Instance.PrivateIp
  MasterEc2InstancePublicIp:
    Description: Master Instance Public IP to acess
    Value: !GetAtt EC2Instance.PublicIp
    Condition: IsAssociatedPublicIp
  MasterEc2InstanceProfileId:
    Description: Instance Profile Id from Distrbution Yaml
    Value: !Ref Ec2InstanceProfile
  MasterSubnetIdDependsOnDNode:
    Description: SubnetId in the vpc for Slave Node
    Value: !Ref PublicSubnetID
  MasterSecurityGroupIdDependsOnDNode:
    Description: Security group id for Slave Node
    Value: !Ref SecurityGroupID
