AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM role and IAM instance profile for raven.
Parameters:
  IamRoleName:
    Description: Name of IAM role.
    Type: String
    Default: Raven_EC2_Role
  IamInstanceProfileName:
    Description: Name of IAM instance profile.
    Type: String
    Default: Raven_EC2_Instance_Profile
Resources:
  IamRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Ref IamRoleName
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: AmazonEc2FullAccess
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - 'ec2:*'
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - 'elasticloadbalancing:*'
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - 'cloudwatch:*'
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - 'autoscaling:*'
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - 'iam:CreateServiceLinkedRole'
                  Resource: '*'
                  Condition:
                    StringEquals:
                      iam:AWSServiceName:
                        - 'utoscaling.amazonaws.com'
                        - 'ec2scheduled.amazonaws.com'
                        - 'elasticloadbalancing.amazonaws.com'
                        - 'spot.amazonaws.com'
                        - 'spotfleet.amazonaws.com'
                        - 'transitgateway.amazonaws.com'
          - PolicyName: AmazonS3FullAccess
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - 's3:*'
                    - 's3-object-lambda:*'
                  Resource: '*'
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn:
      - IamRole
    Properties:
      InstanceProfileName: !Ref IamInstanceProfileName
      Path: /
      Roles:
        - !Ref IamRole
Outputs:
  IamRoleName:
    Description: The name of IAM role.
    Value: !Ref IamRole
    Export:
      Name: !Join [ ":", [ "Raven", "IAM", "Role" ] ]
  IamRoldId:
    Description: The stable and unique string identifying the role.
    Value: !GetAtt IamRole.RoleId
  IamArn:
    Description: The Amazon Resource Name (ARN) for the role.
    Value: !GetAtt IamRole.Arn
  IamInstanceProfileName:
    Description:  The name of the instance profile.
    Value: !Ref IamInstanceProfile
    Export:
      Name: !Join [ ":", [ "Raven", "IAM", "InstanceProfile" ] ]
  IamInstanceProfileArn:
    Description: The Amazon Resource Name (ARN) for the instance profile.
    Value: !GetAtt IamInstanceProfile.Arn
