version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-7s - %(thread)-5d - %(filename)-15s - %(message)-80s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  complex:
    format: '%(asctime)s - %(levelname)-7s - %(threadName)-30s - %(filename)-30s - %(message)-80s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  stdoutHandler:
    level: INFO
    formatter: complex
    class: logging.StreamHandler
    stream: ext://sys.stdout
  stderrHandler:
    level: ERROR
    formatter: complex
    class: logging.StreamHandler
    stream: ext://sys.stderr
  debugFileHandler:
    level: DEBUG
    formatter: complex
    class: configs.RavenFileHandler
    filename: logs/debug.log
    encoding: utf-8
  infoFileHandler:
    class: configs.RavenFileHandler
    filename: logs/info.log
    encoding: utf-8
    level: INFO
    formatter: simple
  errorFileHandler:
    level: ERROR
    formatter: complex
    class: configs.RavenFileHandler
    filename: logs/error.log
    encoding: utf-8
  hookFileHandler:
    level: DEBUG
    formatter: complex
    class: configs.RavenFileHandler
    filename: logs/hook.log
    encoding: utf-8
  generateFileHandler:
    level: DEBUG
    formatter: complex
    class: configs.RavenFileHandler
    filename: logs/generate.log
    encoding: utf-8
  executeFileHandler:
    level: DEBUG
    formatter: complex
    class: configs.RavenFileHandler
    filename: logs/execute.log
    encoding: utf-8
  collectFileHandler:
    level: DEBUG
    formatter: complex
    class: configs.RavenFileHandler
    filename: logs/collect.log
    encoding: utf-8
root:
  level: DEBUG
  handlers:
    - stdoutHandler
    - stderrHandler
    - infoFileHandler
    - errorFileHandler
loggers:
  consoleLogger:
    level: DEBUG
    handlers:
      - stdoutHandler
  hookLogger:
    level: DEBUG
    handlers:
      - hookFileHandler
  generateLogger:
    level: DEBUG
    handlers:
      - generateFileHandler
  executeLogger:
    level: DEBUG
    handlers:
      - executeFileHandler
  collectLogger:
    level: DEBUG
    handlers:
      - collectFileHandler
