version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-7s - %(thread)-5d - %(filename)-15s - %(message)-80s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  complex:
    format: '%(asctime)s - %(levelname)-7s - %(threadName)-30s - %(filename)-30s - %(message)-80s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: complex
    stream: ext://sys.stdout
#  fileHandler:
#    class: logging.FileHandler
#    level: INFO
#    formatter: complex
#    filename: logs/test.log
#  debugTimedRotatingFileHandler:
#    class: logging.handlers.TimedRotatingFileHandler
#    filename: logs/debug.log
#    when: h
#    interval: 1
#    encoding: utf-8
#    level: DEBUG
#    formatter: simple
#  infoTimedRotatingFileHandler:
#    class: logging.handlers.TimedRotatingFileHandler
#    filename: logs/info.log
#    when: h
#    interval: 1
#    encoding: utf-8
#    level: INFO
#    formatter: simple
#  errorTimedRotatingFileHandler:
#    class: logging.handlers.TimedRotatingFileHandler
#    filename: logs/error.log
#    when: h
#    interval: 1
#    encoding: utf-8
#    level: ERROR
#    formatter: simple
root:
  level: DEBUG
  handlers:
    - consoleHandler
#    - debugTimedRotatingFileHandler
#    - infoTimedRotatingFileHandler
#    - errorTimedRotatingFileHandler
loggers:
  console_logger:
    level: DEBUG
    handlers:
      - consoleHandler