version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-7s - %(thread)-5d - %(filename)-15s - %(message)-80s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  fileHandler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/benchmark.log
loggers:
  consoleLogger:
    level: DEBUG
    handlers:
      - consoleHandler
root:
  level: DEBUG
  handlers:
    - consoleHandler
    - fileHandler