version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-7s - %(thread)-5d - %(filename)-15s - %(message)-80s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
#  fileHandler:
#    class: logging.FileHandler
#    level: INFO
#    formatter: simple
#    filename: logs/benchmark.log
  debugTimedRotatingFileHandler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/debug.log
    when: d
    interval: 1
    encoding: utf-8
    level: DEBUG
    formatter: simple
  infoTimedRotatingFileHandler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/info.log
    when: d
    interval: 1
    encoding: utf-8
    level: INFO
    formatter: simple
  errorTimedRotatingFileHandler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/error.log
    when: d
    interval: 1
    encoding: utf-8
    level: ERROR
    formatter: simple
root:
  level: DEBUG
  handlers:
    - consoleHandler
    - debugTimedRotatingFileHandler
    - infoTimedRotatingFileHandler
    - errorTimedRotatingFileHandler
