###############################################################################
# Cloud Provider
###############################################################################

Provider:
  Name: AWS
  Description: Amazon Web Service.
  Properties:
    Region: ap-southeast-1
    KeyName: key_raven
    MasterCount: 1
    SlaveCount: 10

###############################################################################
# Engine
###############################################################################

#Engine:
#  Name: hive
#  Description: Hive.
#  Properties:
#    Concurrency: 10

Engine:
  Name: spark_sql
  Description: Spark-SQL.
  Properties:
    Concurrency: 10


#Engine:
#  Name: presto
#  Description: Presto.
#  Properties:
#    Concurrency: 10

#Engine:
#  Name: athena
#  Description: AWS Athena.
#  Properties:
#    Concurrency: 10


###############################################################################
# Testplan
###############################################################################
# PlanID:
#   Name:
#   Description
#   Properties:
#     Type: The type of test plan, allowed values are pipeline/timeline.
#     Path: The path of test plan config file.
Testplan:
  Name: SSB hybrid 1g timeline test.
  Description:
  Properties:
    Type: Timeline
    Path: configs/testplans/templates/timeline_template.yaml


###############################################################################
# Workload
###############################################################################

Workload:
  ConfigPath: configs/workloads/ssb_hybrid_1g/workload.yaml
  Concurrency: 10
  Distribution: random


###############################################################################
# Metrics and Scores
###############################################################################
#
# Throughput
# ReactionTime
# Latency
# ResponseTime


Metrics:
  # Queries
  - Name: TotalQueries
    Description: Number of queries.
    Type: Integer
  - Name: TotalFinishQueries
    Description: Number of finished queries.
    Type: Integer
  - Name: TotalFailQueris
    Description: Number of failed queries.
    Type: Integer

  # Throughput
  - Name: Throughput
    Description: Throughput(ops/sec).
    Type: Float

  - Name: TOTAL_ELAPSED_TIME
    Description: Total elapsed time.

  # ReactionTime: 查询生成到查询开始执行所经历的时间间隔.
  - Name: AverageReactionTime
    Description: Average reaction time(ms).
    Type: Float
  - Name: MinReactionTime
    Description: Minimum reaction time(ms).
    Type: Float
  - Name: MaxReactionTime
    Description: Maxmium reaction time(ms).
    Type: Float
  - Name: 95thPercentileReactionTime
    Description: 95% percentile reaction time(ms).
    Type: Float

  # Latency: 查询开始执行到查询结束执行所经历的时间间隔.
  - Name: AverageLatency
    Description: Average latency(ms).
    Type: Float
  - Name: MinLatency
    Description: Minimum latency(ms).
    Type: Float
  - Name: MaxLatency
    Description: Maxmium latency(ms).
    Type: Float
  - Name: 95thPercentileLatency.
    Description: 95% percentile latency(ms).
    Type: Float

  # ResponseTime: 查询生成到查询执行结束所经历的时间间隔.
  - Name: AverageResponseTime
    Description: Average response time(ms).
    Type: Float
  - Name: MinResponseTime
    Description: Minimum response time(ms).
    Type: Float
  - Name: MaxResponseTime
    Description: Maxmium response time(ms).
    Type: Float
  - Name: 95thPercentileResponseTime
    Description: 95% percentile response time(ms).
    Type: Float

  # Cost
  - Name: TotalCost
    Description: Total cost($).
    Type: Float
  - Name: PreComputingCost
    Description: Pre computing cost($).
    Type: Float
  - Name: QueryCost
    Description: Query cost($).
    Type: Float

  # CPU Utilization
  - Name: AverageCPUUtilization

  # Memory Utilization
  - Name:

  # Disk Utilization

Scores:
  Offline:
    Calculation:
    Delay:
  Online:
    Calculation:
    Delay: