###############################################################################
# Cloud Provider
###############################################################################

Provider:
  Name: AWS
  Description: Amazon Web Service.
  Properties:
    Region: ap-southeast-1
    KeyName: key_raven

###############################################################################
# Engine
###############################################################################

Engine:
  Name: athena
  Description: AWS Athena.
  Properties:
    Concurrency: 10

#Engine:
#  Name: spark_sql
#  Description: Spark-SQL.

###############################################################################
# Test Plan
###############################################################################
# PlanID:
#   Name:
#   Description
#   Properties:
#     Type: The type of test plan, allowed values are pipeline/timeline.
#     Path: The path of test plan config file.
Testplan:
  Name: SSB hybrid 1g timeline test.
  Description:
  Properties:
    Type: Timeline
    Path: configs/testplans/templates/timeline_template.yaml


###############################################################################
# Workload
###############################################################################

Workload:
  Name: ssb_hybrid_1g
  Description: Workload for test.


###############################################################################
# Metrics
###############################################################################

Metircs:
  - Name: query_latency
    Description: Latency of query.
    Type: Float
    Unit: Second
