Name: SSB
Database: ssb
Queries:
  - Name: Q1.1
    SQL: |
      SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS REVENUE
      FROM LINEORDER, DATES
      WHERE LO_ORDERDATE = D_DATEKEY
      	AND D_YEAR = 1993
      	AND LO_DISCOUNT BETWEEN 1 AND 3
      	AND LO_QUANTITY < 25
  - Name: Q1.2
    SQL: |
      SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS REVENUE
      FROM LINEORDER, DATES
      WHERE LO_ORDERDATE = D_DATEKEY
      	AND D_YEARMONTH = 'Jan1994'
      	AND LO_DISCOUNT BETWEEN 4 AND 6
      	AND LO_QUANTITY BETWEEN 26 AND 35
  - Name: Q1.3
    SQL: |
      SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS REVENUE
      FROM LINEORDER, DATES
      WHERE LO_ORDERDATE = D_DATEKEY
        AND D_WEEKNUMINYEAR = 6
        AND D_YEAR = 1994
        AND LO_DISCOUNT BETWEEN 5 AND 7
        AND LO_QUANTITY BETWEEN 26 AND 35
